name: v*.*.* -PR-> master

on:
  push:
    branches: [ v*.*.* ]

# git ls-remote <URL> | head -1 | sed "s/HEAD//"
jobs:
  # isolate signing & repo cloning from docker image
  auto-pr:
    name: Automated Master Branch PR
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    steps:
          # ref.: https://github.com/actions/checkout, v2.4.0
          - name: Checkout repository & extract branch names 
            uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
            with:
              fetch-depth: 0
          - name: Extract branch name on pull request
            shell: bash
            run: |
              set -x
              git branch -r -l
              git config --global --add safe.directory /github/workspace
              echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
              echo "DEFAULT_BRANCH=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
          - name: Print debug data before publishing
            run: |
              echo " Source branch: ${{ env.DEFAULT_BRANCH }}"
              echo "Default branch: ${{ env.SOURCE_BRANCH }}"
              echo "    Event name: ${{ github.event_name }}"
              echo "    Repo. name: ${{ github.event.repository.name }}"
          - name: Create PR from a version branch to master after version branch push
            if: startsWith(env.SOURCE_BRANCH, 'v') && contains(env.SOURCE_BRANCH, '.') && !contains(env.SOURCE_BRANCH, '-') && !contains(env.SOURCE_BRANCH, 'rc')
            uses: repo-sync/pull-request@5ba2c80b97c87b9174c1548141b7acd80f6376e1
            with:
              github_token: ${{ secrets.REPO_ACCESS }}
              source_branch: ${{ env.SOURCE_BRANCH }}
              destination_branch: ${{ env.DEFAULT_BRANCH}}
              pr_title: "${{ env.SOURCE_BRANCH }} -> ${{ env.DEFAULT_BRANCH }}" 
              pr_label: "kira-automation"
              pr_assignee: "asmodat"
              pr_allow_empty: true